import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';

export default function Home() {
  const [spinResultArray, setSpinResultArray] = useState([])
  const [spinCredits, setSpinCredits] = useState(10)
  function getRandomInt(max) {
    return Math.floor(Math.random() * max);
  }
  const handleSpin = () => {
  if (spinCredits > 0) {
  let tempArray = []
  let tempCredits = spinCredits - 1
  tempArray[0]=getRandomInt(4);
  tempArray[1]=getRandomInt(4);
  tempArray[2]=getRandomInt(4);
  setSpinResultArray(tempArray);
  if (tempArray.toString() === [0,0,0].toString()){
    setSpinCredits(tempCredits+10)
    console.log("cherry")
  }
  else if (tempArray.toString() === [1,1,1].toString()){
    setSpinCredits(tempCredits+20)
    console.log("lemon")
  }
  else if (tempArray.toString() === [2,2,2].toString()){
    setSpinCredits(tempCredits+30)
    console.log("orange")
  }
  else if (tempArray.toString() === [3,3,3].toString()){
    setSpinCredits(tempCredits+40)
    console.log("watermellon")
  }
  else
  setSpinCredits(tempCredits)
  if (tempCredits===0) { alert("Game Over!") }
}
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>WinBig!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/siteicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to WinBig!
        </h1>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Card 1 </h2>
            {spinResultArray[0]===0 ? 
            <img src="cherry.svg"/>: <></>}
            {spinResultArray[0]===1 ? 
            <img src="lemon.svg"/>: <></>}
            {spinResultArray[0]===2 ? 
            <img src="orange.svg"/>: <></>}
            {spinResultArray[0]===3 ? 
            <img src="watermellon.svg"/>: <></>}
          </a>
        </div>
        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Card 2 </h2>
            {spinResultArray[1]===0 ? 
            <img src="cherry.svg"/>: <></>}
            {spinResultArray[1]===1 ? 
            <img src="lemon.svg"/>: <></>}
            {spinResultArray[1]===2 ? 
            <img src="orange.svg"/>: <></>}
            {spinResultArray[1]===3 ? 
            <img src="watermellon.svg"/>: <></>}
          </a>
        </div>
        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Card 3 </h2>
            {spinResultArray[2]===0 ? 
            <img src="cherry.svg"/>: <></>}
            {spinResultArray[2]===1 ? 
            <img src="lemon.svg"/>: <></>}
            {spinResultArray[2]===2 ? 
            <img src="orange.svg"/>: <></>}
            {spinResultArray[2]===3 ? 
            <img src="watermellon.svg"/>: <></>}
          </a>
        </div>
        <div>
        < div className={styles.grid}>
          {(spinResultArray.toString() === [0,0,0].toString()) ? 
          <div> You win 10 </div> : <></>}
          </div>
          < div className={styles.grid}>

          {(spinResultArray.toString() === [1,1,1].toString()) ? 
          <div> You win 20! </div> : <></>}
          </div>
          < div className={styles.grid}>

          {(spinResultArray.toString() === [2,2,2].toString()) ? 
          <div> You win 30! </div> : <></>}
          </div>
          < div className={styles.grid}>

          {(spinResultArray.toString() === [3,3,3].toString()) ? 
          <div> You win 40! </div> : <></>}
          </div>
        < button className='spin-button' onClick={() => { handleSpin() }}>Try your luck!</button>
        < div className={styles.grid}>
          <a className={styles.card}></a>
          <h2>Credits {spinCredits} </h2>
        </div>
        </div>
      </main>

      <footer className={styles.footer}>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo 2.png" alt="WinBig" width={72} height={16} />
          </span>
      </footer>
    </div>
  )
}
